// +build novnc_error404_generate

package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	fmt.Println("writing error404_generated.go")

	buf, err := ioutil.ReadFile("error404.html")
	if err != nil {
		panic(err)
	}

	f, err := os.Create("error404_generated.go")
	if err != nil {
		panic(err)
	}

	_, err = fmt.Fprintf(f, "// Code generated by error404_generate.go; DO NOT EDIT.\n\npackage novnc\n\nimport \"html/template\"\n\nvar Error404TMPL = template.Must(template.New(\"\").Parse(%#v))\n", string(buf))
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
