// +build novnc_index_generate

package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	fmt.Println("writing index_generated.go")

	buf, err := ioutil.ReadFile("index.html")
	if err != nil {
		panic(err)
	}

	f, err := os.Create("index_generated.go")
	if err != nil {
		panic(err)
	}

	_, err = fmt.Fprintf(f, "// Code generated by index_generate.go; DO NOT EDIT.\n\npackage novnc\n\nimport \"html/template\"\n\nvar IndexTMPL = template.Must(template.New(\"\").Parse(%#v))\n", string(buf))
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
